#version: '3.8'
#
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
    environment:
      APP_URL: http://localhost:8080
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 587
      MAIL_USERNAME: d9c3fd24f6a390
      MAIL_PASSWORD: d034008c5fa1b8
      MAIL_FROM_ADDRESS: no-reply@darikruv.bg
      MAIL_FROM_NAME: DariKruv
      FCM_VAPID_PUBLIC_KEY: BNw626BdNhNwM8Pg_Mlrf0u6ir0PGgAbKm3FoeYyEaV25v_Vh520UscI9bkqP44ovdSq652EpKN3R6IfWPpmaKE
      FIREBASE_API_KEY: AIzaSyBY0EhX1SLvCKhGr89edAA6JVIXaIfVmQU
      FIREBASE_AUTH_DOMAIN: darikruv-f5c18.firebaseapp.com
      FIREBASE_PROJECT_ID: darikruv-f5c18
      FIREBASE_STORAGE_BUCKET: darikruv-f5c18.firebasestorage.app
      FIREBASE_MESSAGING_SENDER_ID: 853622303882
      FIREBASE_APP_ID: 1:853622303882:web:55de63b5bc0f9c9c599173
      FIREBASE_SERVICE_ACCOUNT_JSON: ""
      FIREBASE_SERVICE_ACCOUNT_JSON_BASE64: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZGFyaWtydXYtZjVjMTgiLAogICJwcml2YXRlX2tleV9pZCI6ICI0NWIxNTg2OTI3NjcyMzM2NDAzNmVhMGQ0NzliM2ExYTFhNzc3ZWFhIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURHeHNRaUwwSy9zWVpVXG5EWFRWWEFudUVWMS8zdVBTTXZZcldQbTRWV3ZjNU9wMVpHNTdaVVQzRmlBYTd0ZDRIQlB3MW1jc2RuOHBvcHltXG5wdnkralg1cmFEaTVhajJ3dlBySG9teFhOV2RxaFVydExGSmlCbXRobnVDdld3UjNWZG5URGZlcnVNQkcvZlozXG5qUkVhR1lETlpJUGowYkJydVJjM0JncyszTFg2QXI0a2FpakNvdk1tTzljdG1aeS9xVGNDaWY1MFltdmlVU2R6XG5xZXZ5cnVXc3hUenZiV3hwU2hGYUpucFFYMXNzS1BTVVhlWnc5b0ZQT1BOS25JL2tWZHJMbFpOWTZxaHJsZnlXXG43TENrNnhXQVA4VHZ1L3lGNmloOFpEUFcyR3JDbDdYZjN0ZTU3djd3eFJGVWtDS2hEdEtJOGVuVDRZNXFTcnNJXG5XL3RMb0VJdkFnTUJBQUVDZ2dFQU5zRm9JOWFLOTQwcWFKcndWUm11YnBNQUE0cGRqWGlXVVNpSVdadkdRNm9YXG5YOUVUa2hBNmFDb0RIQWd3K0pnYmNodE5mblVCNEhFMzM3eGVJUXVQQ0gxRUt1YzJLU3BWbG9xS2Q1ZHhibWxiXG5VMndESVplTkd1NE9ESi93NGdLWEowbFFzVkFLUDBRVUVhaWRUbWc2RDlvaGJxOURmdGtVcVFhVU1IUFIrUlV1XG5EWXFpNHl4UWllM2pRMWFWbjZvMXJuRFhyK2hyOE1mcFQ4VU1tRi81SzltQUdWd3dtU05Qek9jRDF0VlpycUMwXG5tQ3JiVm1Ja0F0U2ZTalBkUDNMYk1kbzF1YlRvamxBTHRkVjBlOEhtanhXaS8xWHdoUGZpeTNlaGowUTJOb09ZXG5xbUtZNGtJNXJScEg0Mlo5TzF3YnlmcnZTeHJaTlhTM2VwWFhFRkFXSVFLQmdRRGlqYmh2NjZ4TTVCL2lkVkRLXG43TUZaOC9IcmxHMkl4SEFkcXRyQ3RBaVVXMXdVbVpUeGV3MWRHRkhZSWRNSWM5YnQwU29NN0RPbUgzSHRJRWwrXG56OHBaaytENDM4MUdVNnNqUXF5UUptSEw3VDZKVTkxR0JkNllVN0pIZCtHakpVUVQ4OGVCNjIxbnExU1NUM1lRXG5oR3hUTmpGK25TcHdJd0J5ZTJnNGRMcTlNUUtCZ1FEZ25NdldIR05nREJxYkp4OEVJZk16OWJwdVlvc0E5cmIyXG5wVEpyVWRlTFk3andCdFAxREZSUXc1SUF6MnhBOTJPL3RMdG9aY2pEakZhcnAyVGUrZW1jaE9YeGVMSE9jWGtDXG5BQm5ybFgwdjNZR1g0YTVxa0tpdm9uVG5oYzY2TUlYTTZ1eTBjdnZpV2loZjJ4UnEvMGEvWTZ4QUU0RFJHcU1OXG4xdFB4OGQyZFh3S0JnUUNiU1ZySFZEbll4bkRZYjJNK2hJT1BYYmRQcTRCY3c1QzV0UmVYWjRHTjl3VXBsWS9TXG42VzVpaGozck1Gd1BLaCtEQ09DUzFRQWQrT1hGREdGMEM0ZCtXTzlXaDBpVDBOdTRJb1pYbEFkcW1TWkpTUE9kXG5nSDV2Mk1hVldDV1FCd1lmeXZQUUtJZm9ERGEreHJwOVhkZEdQaG8wMkJOem8zbzEva0tVbCtZN3NRS0JnUUN1XG5SUGxpQm1TVUFOQWowUmFmZmpmVCtMUE5NV2ZvTjROOW1tNmtGYnZHeW5pU3dybHhSeitqNmhrOXg3R1dObHVPXG5RZ3VsMUZNUVpiSlpQR2RuR1QvSDBOVVhwUzFQbjNyanNuQnArSEpJMFBQYmc1NXYwQTBST0ZxN3gzVzl3Q2dQXG45Ylh4eThUaXVsRFpEb0dwQXFkQmwzUHR3elFQQ1R1NVlSVFFnM2dPd1FLQmdEanNTeDVWUkNPM21ER2VXaGhvXG5CMGdrNkZzNVJkcFBYeFQ4WnBYMGZXRXpKdHZIVTVZaWZUN3VVaTRYeXRGTFBYVDY2UlBGL3lWRWI2NUVKY0s1XG5rc0xINzhIQVBtZWd3cXpLNUNtcVRLRDlOM2pNdEorQU1YSGJDa0hUd0xSb2JEOHA1RjJnam1WeHJLMHdNZEsrXG5meFYrcVQvOWF5aEFSK29icDdacEw4ZnBcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJmaXJlYmFzZS1hZG1pbnNkay1mYnN2Y0BkYXJpa3J1di1mNWMxOC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDc5MTcwOTE0NDk4Mjg5NDQzNDUiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLWZic3ZjJTQwZGFyaWtydXYtZjVjMTguaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: darikruv
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
